import Menu from '@/components/base/Menu/Menu'
import './globals.css'
import InfoBoard from '@/components/dashboard/InfoBoard/InfoBoard'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Menu/>
        {children}
      </body>
    </html>
  )
}
